package com.hello.utils

import org.json.JSONException
import org.json.JSONObject

object CityListUtil {
    private fun getCityList() = JSONObject(
            "{\n" +
                    "“北京”: “Beijing”,\n" +
                    "“天津”: “Tianjin”,\n" +
                    "“上海”: “Shanghai”,\n" +
                    "“重庆”: “Chongqing”,\n" +
                    "“银川”: “Yinchuan”,\n" +
                    "“石嘴山”: “Shizuishan”,\n" +
                    "“Wuzhong”: “吴忠”,\n" +
                    "“Guyuan”: “固原”,\n" +
                    "“Zhongwei”: “中卫”,\n" +
                    "“Wulumuqi”: “乌鲁木齐”,\n" +
                    "“Kelamayi”: “克拉玛依”,\n" +
                    "“Lasa”: “拉萨”,\n" +
                    "“Huhehaote”: “呼和浩特”,\n" +
                    "“Baotou”: “包头”,\n" +
                    "“Wuhai”: “乌海”,\n" +
                    "“Chifeng”: “赤峰”,\n" +
                    "“Tongliao”: “通辽”,\n" +
                    "“Eerduosi”: “鄂尔多斯”,\n" +
                    "“Hulunbeier”: “呼伦贝尔”,\n" +
                    "“Bayannaoer”: “巴彦淖尔”,\n" +
                    "“Wulanchabu”: “乌兰察布”,\n" +
                    "“Nanning”: “南宁”,\n" +
                    "“Liuzhou”: “柳州”,\n" +
                    "“Guilin”: “桂林”,\n" +
                    "“Wuzhou”: “梧州”,\n" +
                    "“Beihai”: “北海”,\n" +
                    "“Chongzuo”: “崇左”,\n" +
                    "“Laibin”: “来宾”,\n" +
                    "“Hezhou”: “贺州”,\n" +
                    "“Yulin”: “玉林”,\n" +
                    "“Baise”: “百色”,\n" +
                    "“Hechi”: “河池”,\n" +
                    "“Qinzhou”: “钦州”,\n" +
                    "“Fangchenggang”: “防城港”,\n" +
                    "“Guigang”: “贵港”,\n" +
                    "“Haerbin”: “哈尔滨”,\n" +
                    "“Daqing”: “大庆”,\n" +
                    "“Qiqihaer”: “齐齐哈尔”,\n" +
                    "“Jiamusi”: “佳木斯”,\n" +
                    "“Jixi”: “鸡西”,\n" +
                    "“Hegang”: “鹤岗”,\n" +
                    "“Shuangyashan”: “双鸭山”,\n" +
                    "“Mudanjiang”: “牡丹江”,\n" +
                    "“Yichun”: “伊春”,\n" +
                    "“Qitaihe”: “七台河”,\n" +
                    "“Heihe”: “黑河”,\n" +
                    "“Suihua”: “绥化”,\n" +
                    "“Changchun”: “长春”,\n" +
                    "“Jilin”: “吉林”,\n" +
                    "“Siping”: “四平”,\n" +
                    "“Liaoyuan”: “辽源”,\n" +
                    "“Tonghua”: “通化”,\n" +
                    "“Baishan”: “白山”,\n" +
                    "“Songyuan”: “松原”,\n" +
                    "“Baicheng”: “白城”,\n" +
                    "“Shenyang”: “沈阳”,\n" +
                    "“Dalian”: “大连”,\n" +
                    "“Anshan”: “鞍山”,\n" +
                    "“Fushun”: “抚顺”,\n" +
                    "“Benxi”: “本溪”,\n" +
                    "“Dandong”: “丹东”,\n" +
                    "“Jinzhou”: “锦州”,\n" +
                    "“Yingkou”: “营口”,\n" +
                    "“Fuxin”: “阜新”,\n" +
                    "“Liaoyang”: “辽阳”,\n" +
                    "“Panjin”: “盘锦”,\n" +
                    "“Tieling”: “铁岭”,\n" +
                    "“Chaoyang”: “朝阳”,\n" +
                    "“Huludao”: “葫芦岛”,\n" +
                    "“Shijiazhuang”: “石家庄”,\n" +
                    "“Tangshan”: “唐山”,\n" +
                    "“Handan”: “邯郸”,\n" +
                    "“Qinghuangdao”: “秦皇岛”,\n" +
                    "“Baoding”: “保定”,\n" +
                    "“Zhangjiakou”: “张家口”,\n" +
                    "“Chengde”: “承德”,\n" +
                    "“Langfang”: “廊坊”,\n" +
                    "“Cangzhou”: “沧州”,\n" +
                    "“Hengshui”: “衡水”,\n" +
                    "“Xingtai”: “邢台”,\n" +
                    "“Jinan”: “济南”,\n" +
                    "“Qingdao”: “青岛”,\n" +
                    "“Zibo”: “淄博”,\n" +
                    "“Zaozhuang”: “枣庄”,\n" +
                    "“Dongying”: “东营”,\n" +
                    "“Yantai”: “烟台”,\n" +
                    "“Weifang”: “潍坊”,\n" +
                    "“Jining”: “济宁”,\n" +
                    "“Taian”: “泰安”,\n" +
                    "“Weihai”: “威海”,\n" +
                    "“Rizhao”: “日照”,\n" +
                    "“Laiwu”: “莱芜”,\n" +
                    "“Linyi”: “临沂”,\n" +
                    "“Dezhou”: “德州”,\n" +
                    "“Liaocheng”: “聊城”,\n" +
                    "“Heze”: “菏泽”,\n" +
                    "“Binzhou”: “滨州”,\n" +
                    "“Nanjing”: “南京”,\n" +
                    "“Zhenjiang”: “镇江”,\n" +
                    "“Changzhou”: “常州”,\n" +
                    "“Wuxi”: “无锡”,\n" +
                    "“Suzhou”: “苏州”,\n" +
                    "“Xuzhou”: “徐州”,\n" +
                    "“Lianyungang”: “连云港”,\n" +
                    "“Huaian”: “淮安”,\n" +
                    "“Yancheng”: “盐城”,\n" +
                    "“Yangzhou”: “扬州”,\n" +
                    "“Taizhou”: “泰州”,\n" +
                    "“Nantong”: “南通”,\n" +
                    "“Suqian”: “宿迁”,\n" +
                    "“Hefei”: “合肥”,\n" +
                    "“Bengbu”: “蚌埠”,\n" +
                    "“Wuhu”: “芜湖”,\n" +
                    "“Huainan”: “淮南”,\n" +
                    "“Bozhou”: “亳州”,\n" +
                    "“Fuyang”: “阜阳”,\n" +
                    "“Huaibei”: “淮北”,\n" +
                    "“Suzhou”: “宿州”,\n" +
                    "“Chuzhou”: “滁州”,\n" +
                    "“Anqing”: “安庆”,\n" +
                    "“Chaohu”: “巢湖”,\n" +
                    "“Maanshan”: “马鞍山”,\n" +
                    "“Xuancheng”: “宣城”,\n" +
                    "“Huangshan”: “黄山”,\n" +
                    "“Chizhou”: “池州”,\n" +
                    "“Tongling”: “铜陵”,\n" +
                    "“Hangzhou”: “杭州”,\n" +
                    "“Jiaxing”: “嘉兴”,\n" +
                    "“Huzhou”: “湖州”,\n" +
                    "“Ningbo”: “宁波”,\n" +
                    "“Jinhua”: “金华”,\n" +
                    "“Wenzhou”: “温州”,\n" +
                    "“Lishui”: “丽水”,\n" +
                    "“Shaoxing”: “绍兴”,\n" +
                    "“Quzhou”: “衢州”,\n" +
                    "“Zhoushan”: “舟山”,\n" +
                    "“Taizhou”: “台州”,\n" +
                    "“Fuzhou”: “福州”,\n" +
                    "“Xiamen”: “厦门”,\n" +
                    "“Quanzhou”: “泉州”,\n" +
                    "“Sanming”: “三明”,\n" +
                    "“Nanping”: “南平”,\n" +
                    "“Zhangzhou”: “漳州”,\n" +
                    "“Putian”: “莆田”,\n" +
                    "“Ningde”: “宁德”,\n" +
                    "“Longyan”: “龙岩”,\n" +
                    "“Guangzhou”: “广州”,\n" +
                    "“Shenzhen”: “深圳”,\n" +
                    "“Shantou”: “汕头”,\n" +
                    "“Huizhou”: “惠州”,\n" +
                    "“Zhuhai”: “珠海”,\n" +
                    "“Jieyang”: “揭阳”,\n" +
                    "“Foshan”: “佛山”,\n" +
                    "“Heyuan”: “河源”,\n" +
                    "“Yangjiang”: “阳江”,\n" +
                    "“Maoming”: “茂名”,\n" +
                    "“Zhanjiang”: “湛江”,\n" +
                    "“Meizhou”: “梅州”,\n" +
                    "“Zhaoqing”: “肇庆”,\n" +
                    "“Shaoguan”: “韶关”,\n" +
                    "“Chaozhou”: “潮州”,\n" +
                    "“Dongguan”: “东莞”,\n" +
                    "“Zhongshan”: “中山”,\n" +
                    "“Qingyuan”: “清远”,\n" +
                    "“Jiangmen”: “江门”,\n" +
                    "“Shanwei”: “汕尾”,\n" +
                    "“Yunfu”: “云浮”,\n" +
                    "“Haikou”: “海口”,\n" +
                    "“Sanya”: “三亚”,\n" +
                    "“Kunming”: “昆明”,\n" +
                    "“Qujing”: “曲靖”,\n" +
                    "“Yuxi”: “玉溪”,\n" +
                    "“Baoshan”: “保山”,\n" +
                    "“Zhaotong”: “昭通”,\n" +
                    "“Lijiang”: “丽江”,\n" +
                    "“Puer”: “普洱”,\n" +
                    "“Lincang”: “临沧”,\n" +
                    "“Guiyang”: “贵阳”,\n" +
                    "“Liupanshui”: “六盘水”,\n" +
                    "“Zunyi”: “遵义”,\n" +
                    "“Anshun”: “安顺”,\n" +
                    "“成都”: “Chengdu”,\n" +
                    "“Mianyang”: “绵阳”,\n" +
                    "“Deyang”: “德阳”,\n" +
                    "“Guangyuan”: “广元”,\n" +
                    "“自贡”: “Zigong”,\n" +
                    "“Panzhihua”: “攀枝花”,\n" +
                    "“Leshan”: “乐山”,\n" +
                    "“Nanchong”: “南充”,\n" +
                    "“Neijiang”: “内江”,\n" +
                    "“Suining”: “遂宁”,\n" +
                    "“Guangan”: “广安”,\n" +
                    "“Luzhou”: “泸州”,\n" +
                    "“Dazhou”: “达州”,\n" +
                    "“Meishan”: “眉山”,\n" +
                    "“Yibin”: “宜宾”,\n" +
                    "“Yaan”: “雅安”,\n" +
                    "“Ziyang”: “资阳”,\n" +
                    "“Changsha”: “长沙”,\n" +
                    "“Zhuzhou”: “株洲”,\n" +
                    "“Xiangtan”: “湘潭”,\n" +
                    "“Hengyang”: “衡阳”,\n" +
                    "“Yueyang”: “岳阳”,\n" +
                    "“Chenzhou”: “郴州”,\n" +
                    "“Yongzhou”: “永州”,\n" +
                    "“Shaoyang”: “邵阳”,\n" +
                    "“Huaihua”: “怀化”,\n" +
                    "“Changde”: “常德”,\n" +
                    "“Yiyang”: “益阳”,\n" +
                    "“Zhangjiajie”: “张家界”,\n" +
                    "“Loudi”: “娄底”,\n" +
                    "“Wuhan”: “武汉”,\n" +
                    "“Xiangfan”: “襄樊”,\n" +
                    "“Yichang”: “宜昌”,\n" +
                    "“Huangshi”: “黄石”,\n" +
                    "“Ezhou”: “鄂州”,\n" +
                    "“Suizhou”: “随州”,\n" +
                    "“Jingzhou”: “荆州”,\n" +
                    "“Jingmen”: “荆门”,\n" +
                    "“Shiyan”: “十堰”,\n" +
                    "“Xiaogan”: “孝感”,\n" +
                    "“Huanggang”: “黄冈”,\n" +
                    "“Xianning”: “咸宁”,\n" +
                    "“Zhengzhou”: “郑州”,\n" +
                    "“Luoyang”: “洛阳”,\n" +
                    "“Kaifeng”: “开封”,\n" +
                    "“Luohe”: “漯河”,\n" +
                    "“Anyang”: “安阳”,\n" +
                    "“Xinxiang”: “新乡”,\n" +
                    "“Zhoukou”: “周口”,\n" +
                    "“Sanmenxia”: “三门峡”,\n" +
                    "“Jiaozuo”: “焦作”,\n" +
                    "“Pingdingshan”: “平顶山”,\n" +
                    "“Xinyang”: “信阳”,\n" +
                    "“Nanyang”: “南阳”,\n" +
                    "“Hebi”: “鹤壁”,\n" +
                    "“Puyang”: “濮阳”,\n" +
                    "“Xuchang”: “许昌”,\n" +
                    "“Shangqiu”: “商丘”,\n" +
                    "“Zhumadian”: “驻马店”,\n" +
                    "“Taiyuan”: “太原”,\n" +
                    "“DaTong”: “大同”,\n" +
                    "“Xinzhou”: “忻州”,\n" +
                    "“Yangquan”: “阳泉”,\n" +
                    "“Changzhi”: “长治”,\n" +
                    "“Jincheng”: “晋城”,\n" +
                    "“Shuozhou”: “朔州”,\n" +
                    "“Jinzhong”: “晋中”,\n" +
                    "“Yuncheng”: “运城”,\n" +
                    "“Linfen”: “临汾”,\n" +
                    "“Lvliang”: “吕梁”,\n" +
                    "“Xian”: “西安”,\n" +
                    "“Xianyang”: “咸阳”,\n" +
                    "“Tongchuan”: “铜川”,\n" +
                    "“Yanan”: “延安”,\n" +
                    "“Baoji”: “宝鸡”,\n" +
                    "“Weinan”: “渭南”,\n" +
                    "“Hanzhoung”: “汉中”,\n" +
                    "“Ankang”: “安康”,\n" +
                    "“Shangluo”: “商洛”,\n" +
                    "“Yulin”: “榆林”,\n" +
                    "“Lanzhou”: “兰州”,\n" +
                    "“Tianshui”: “天水”,\n" +
                    "“Pingliang”: “平凉”,\n" +
                    "“Jiuquan”: “酒泉”,\n" +
                    "“Jiayuguan”: “嘉峪关”,\n" +
                    "“Jinchang”: “金昌”,\n" +
                    "“baiyiin”: “白银”,\n" +
                    "“Wuwei”: “武威”,\n" +
                    "“Zhangye”: “张掖”,\n" +
                    "“庆阳”: “Qingyang”,\n" +
                    "“定西”: “Dingxi”,\n" +
                    "“陇南”: “Longnan”,\n" +
                    "“西宁”: “Xining”,\n" +
                    "“南昌”: “Nanchang”,\n" +
                    "“九江”: “Jiujiang”,\n" +
                    "“赣州”: “Ganzhou”,\n" +
                    "“吉安”: “Jian”,\n" +
                    "“鹰潭”: “Yingtan”,\n" +
                    "“上饶”: “Shangrao”,\n" +
                    "“萍乡”: “Pingxiang”,\n" +
                    "“景德镇”: “Jingdezhen”,\n" +
                    "“新余”: “Xinyu”,\n" +
                    "“宜春”: “Yichun”,\n" +
                    "“抚州”: “Fuzhou”\n" +
                    "}"
    )

    @JvmStatic
    fun getCityEnglish(city: String): String {
        val mCity = city.replace("市", "")

        var value = ""
        try {
            value = getCityList().get(mCity).toString()
        } catch (e: JSONException) {
            e.printStackTrace()
        }

        return value
    }
}